//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.Inspeccions = new HashSet<Inspeccion>();
            this.Rentas = new HashSet<Renta>();
        }
    
        public int ID { get; set; }
        public string Descripcion { get; set; }
        public string ChasisNum { get; set; }
        public string MotorNum { get; set; }
        public string PlacaNum { get; set; }
        public Nullable<int> Tipo_Vehiculo { get; set; }
        public Nullable<int> Marca_Vehiculo { get; set; }
        public Nullable<int> Modelo_Vehiculo { get; set; }
        public Nullable<int> Tipo_Combustible_Vehiculo { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspeccion> Inspeccions { get; set; }
        public virtual Marca_Vehiculo Marca_Vehiculo1 { get; set; }
        public virtual Modelo_Vehiculo Modelo_Vehiculo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Renta> Rentas { get; set; }
        public virtual Tipo_Combustible_Vehiculo Tipo_Combustible_Vehiculo1 { get; set; }
        public virtual Tipo_Vehiculo Tipo_Vehiculo1 { get; set; }
    }
}
